In [ ]:
#1Initialize an empty array with size 2X2.
# Initialize a 2x2 array
array = [[0, 0], [0, 0]]  # Optionally, you can initialize with zeros

# Print the array to verify initialization
for row in array:
    print(row)


[0, 0]
[0, 0]


In [ ]:
#2. Initialize an all one array with size 4X2.
import numpy as np

# Initialize a 4x2 array filled with ones
array = np.ones((4, 2))

# Print the array to verify initialization
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#3Return a new array of given shape and type, filled with fill value.{Hint: np.full}
shape = (3, 3)  # Example shape
fill_value = 7  # Example fill value
# creates array with given custom values
filled_array = np.full(shape, fill_value)
print(filled_array)



[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
#4
existing_array = np.array([[1, 2], [3, 4]])  # Example existing array
# prints data type with same shape filled with 0
zeros_like_array = np.zeros_like(existing_array)
print(zeros_like_array)


[[0 0]
 [0 0]]


In [ ]:
#5Return a new array of ones with the same shape and type as a given array

ones_like_array = np.ones_like(existing_array)
print(ones_like_array)


[[1 1]
 [1 1]]


In [4]:
#6Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print(numpy_array)


NameError: name 'np' is not defined

In [ ]:
#4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
#1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
import numpy as np

array_range = np.arange(10, 50)
print(array_range)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(0, 9).reshape(3, 3)
print(matrix_3x3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#4.Create a random array of size 30 value from 0 to 1and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Mean of the array:", mean_value)


Mean of the array: 0.6295622901826553


In [ ]:
#5.Create a 10x10 array with random values and find the minimum and maximum values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.014528758413026699
Maximum value: 0.9990736779075245


In [ ]:
#6.Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Index 4 corresponds to the 5th element
print(zero_array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#7. Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)


[0 4 0 0 2 1]


In [ ]:
#8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))  # Creating a 5x5 array
border_array[1:-1, 1:-1] = 0  # Setting inner elements to 0
print(border_array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1  # Fill 1s in even rows
checkerboard[::2, 1::2] = 1  # Fill 1s in odd rows
print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#Problem - 3: Array Operations:
#For the following arrays:
#x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
#v = np.array([9,10]) and w = np.array([11,12]);
#Complete all the task using numpy:
#1. Add the two array.
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

addition_result = x + y
print("Addition:\n", addition_result)




Addition:
 [[ 6  8]
 [10 13]]


In [ ]:
#2. Subtract the two arrays
subtraction_result = x - y
print("Subtraction:\n", subtraction_result)


Subtraction:
 [[-4 -4]
 [-4 -3]]


In [ ]:
#3. Multiply the array with any integers of your choice
multiplication_result = x * 2  # Multiplying by 2
print("Multiplication by 2:\n", multiplication_result)

Multiplication by 2:
 [[ 2  4]
 [ 6 10]]


In [ ]:
#4. Find the square of each element of the array
squared_result = np.square(x)
print("Square of each element:\n", squared_result)


Square of each element:
 [[ 1  4]
 [ 9 25]]


In [ ]:
#5. Find the dot product
dot_product_vw = np.dot(v, w)  # Dot product of v and w
dot_product_xv = np.dot(x, v)  # Dot product of x and v
dot_product_xy = np.dot(x, y)  # Dot product of x and y

print("Dot product v and w:", dot_product_vw)
print("Dot product x and v:\n", dot_product_xv)
print("Dot product x and y:\n", dot_product_xy)


Dot product v and w: 219
Dot product x and v:
 [29 77]
Dot product x and y:
 [[19 22]
 [50 58]]


In [ ]:
#6. Concatenate x and y along row and v and w along column
concatenated_xy_row = np.concatenate((x, y), axis=0)  # Concatenate along rows
concatenated_vw_column = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)  # Reshape and concatenate along columns

print("Concatenated x and y along rows:\n", concatenated_xy_row)
print("Concatenated v and w along columns:\n", concatenated_vw_column)

Concatenated x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w along columns:
 [[ 9 11]
 [10 12]]


In [ ]:
#7. Concatenate x and v; if you get an error, observe and explain why you got the error
try:
    concatenated_xv = np.concatenate((x, v.reshape(1, -1)), axis=0)  # Attempt to concatenate
except ValueError as e:
    print("Error:", e)

In [ ]:
#Problem - 4: Matrix Operations:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A_inv = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A_inv:\n", identity_matrix)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)
are_equal = np.array_equal(AB, BA)
print("AB equals BA:", are_equal)

# 3. Prove (AB)^T = B^T A^T
AB_transpose = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("Transpose of AB:\n", AB_transpose)
print("B^T * A^T:\n", BT_AT)
is_transpose_equal = np.array_equal(AB_transpose, BT_AT)
print("Transpose of AB equals B^T * A^T:", is_transpose_equal)

# Solve the system of linear equations
A_coeff = np.array([[2, -3, 1],
                    [1, -1, 2],
                    [3, 1, -1]])
B_const = np.array([-1, -3, 9])

# Solve for X using Inverse Method
X = np.linalg.inv(A_coeff).dot(B_const)
print("Solution using Inverse Method:\n", X)


A * A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB equals BA: False
Transpose of AB:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Transpose of AB equals B^T * A^T: True
Solution using Inverse Method:
 [ 2.  1. -2.]
